#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/sdk:5.0.403


pipelines:
  branches:
    main:
      - step:
          name: 'Package'
          caches:
            - dotnetcore
          script:
            - apt-get update
            - apt-get install zip -y
            - dotnet build
            - dotnet publish ./web/web.csproj -c Release -o ./publish
            - cd ./publish
            - zip -r web.zip .
          artifacts:
            - 'publish/web/web.zip'
      - step:
          name: Deploy to stg
          deployment: test
          trigger: manual
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.3
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: 'House-of-Griffin'
                AZURE_APP_NAME: 'houseofgriffin-api-stg'
                ZIP_FILE: 'publish/web.zip'


  