// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using griffined_api.Data;

#nullable disable

namespace griffinedapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230628064151_StudentIdPkAttemptedFix")]
    partial class StudentIdPkAttemptedFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("griffined_api.Models.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentId")
                        .HasColumnType("int");

                    b.Property<string>("subdistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("studentId")
                        .IsUnique()
                        .HasFilter("[studentId] IS NOT NULL");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("appointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("appointmentType")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.AppointmentMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("appointmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("teacherId");

                    b.ToTable("AppointmentMember", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.CancellationRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("classId")
                        .HasColumnType("int");

                    b.Property<string>("requestedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyClassId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.HasIndex("studyClassId");

                    b.HasIndex("studyCourseId");

                    b.HasIndex("teacherId");

                    b.ToTable("CancellationRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("staffId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("registrationRequestId");

                    b.HasIndex("staffId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.CourseMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studySubjectId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.HasIndex("studySubjectId");

                    b.ToTable("CourseMember", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Level", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("courseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.ToTable("Level", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.NewCourseRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("courseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("levelId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("method")
                        .HasColumnType("int");

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("totalHours")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.HasIndex("levelId");

                    b.HasIndex("registrationRequestId");

                    b.ToTable("NewCourseRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.NewCourseSubjectRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("hour")
                        .HasColumnType("int");

                    b.Property<int?>("newCourseRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("subjectId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("newCourseRequestId");

                    b.HasIndex("subjectId");

                    b.ToTable("NewCourseSubjectRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Parent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId")
                        .IsUnique();

                    b.ToTable("Parent", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("registrationRequestId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.PreferredDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("toTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("studyCourseId");

                    b.ToTable("PreferredDay", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.PreferredDayRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("toTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("registrationRequestId");

                    b.ToTable("PreferredDayRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.RegistrationRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("byEAId")
                        .HasColumnType("int");

                    b.Property<int>("byECId")
                        .HasColumnType("int");

                    b.Property<int>("byOAId")
                        .HasColumnType("int");

                    b.Property<int>("cancelledBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hasSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("newCourseDetailError")
                        .HasColumnType("bit");

                    b.Property<bool>("paymentError")
                        .HasColumnType("bit");

                    b.Property<int>("paymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("paymentType")
                        .HasColumnType("int");

                    b.Property<int>("registrationStatus")
                        .HasColumnType("int");

                    b.Property<bool>("scheduleError")
                        .HasColumnType("bit");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RegistrationRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.RegistrationRequestMember", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("registrationRequestId");

                    b.HasIndex("studentId");

                    b.ToTable("RegistrationRequestMember", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("appointmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("toTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Staff", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firebaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StaffNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hasRead")
                        .HasColumnType("bit");

                    b.Property<int?>("staffId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("staffId");

                    b.HasIndex("studyCourseId");

                    b.ToTable("StaffNotification", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("autoIncrementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("autoIncrementId"));

                    b.Property<string>("countryOfSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("dob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firebaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("healthInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hogInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("levelOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("school")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("targetScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("targetUni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudentAddingRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("registrationRequestId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("registrationRequestId")
                        .IsUnique();

                    b.HasIndex("studyCourseId");

                    b.ToTable("StudentAddingRequest", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudentAdditionalFile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("file")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.ToTable("StudentAdditionalFile", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudentAttendance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attendance")
                        .HasColumnType("int");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyClassId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId")
                        .IsUnique();

                    b.HasIndex("studyClassId");

                    b.ToTable("StudentAttendance", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudentNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hasRead")
                        .HasColumnType("bit");

                    b.Property<int?>("studentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studentId");

                    b.HasIndex("studyCourseId");

                    b.ToTable("StudentNotification", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudentReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("courseMemberId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("dateUpdated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateUploaded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("progression")
                        .HasColumnType("int");

                    b.Property<string>("report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("courseMemberId");

                    b.HasIndex("teacherId");

                    b.ToTable("StudentReport", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudyClass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("classNumber")
                        .HasColumnType("int");

                    b.Property<bool>("isMakeup")
                        .HasColumnType("bit");

                    b.Property<int?>("scheduleId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int?>("studySubjectId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scheduleId")
                        .IsUnique();

                    b.HasIndex("studySubjectId");

                    b.HasIndex("teacherId");

                    b.ToTable("StudyClass", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudyCourse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("courseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.ToTable("StudyCourse", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudyCourseHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("dateUpdated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("staffId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("staffId");

                    b.HasIndex("studyCourseId");

                    b.ToTable("StudyCourseHistory", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.StudySubject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("subjectId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("studyCourseId");

                    b.HasIndex("subjectId");

                    b.ToTable("StudySubject", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Subject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("courseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("courseId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firebaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.TeacherNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("appointmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hasRead")
                        .HasColumnType("bit");

                    b.Property<int?>("studyCourseId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("teacherId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("appointmentId");

                    b.HasIndex("studyCourseId");

                    b.HasIndex("teacherId");

                    b.ToTable("TeacherNotification", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.WorkTime", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacherId")
                        .HasColumnType("int");

                    b.Property<string>("toTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("teacherId");

                    b.ToTable("WorkTime", (string)null);
                });

            modelBuilder.Entity("griffined_api.Models.Address", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithOne("address")
                        .HasForeignKey("griffined_api.Models.Address", "studentId");

                    b.Navigation("student");
                });

            modelBuilder.Entity("griffined_api.Models.AppointmentMember", b =>
                {
                    b.HasOne("griffined_api.Models.Appointment", "appointment")
                        .WithMany("appointmentMembers")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("appointmentMembers")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("appointment");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.CancellationRequest", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithMany("cancellationRequests")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyClass", "studyClass")
                        .WithMany("cancellationRequests")
                        .HasForeignKey("studyClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("cancellationRequests")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("cancellationRequests")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("studyClass");

                    b.Navigation("studyCourse");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.Comment", b =>
                {
                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithMany("comments")
                        .HasForeignKey("registrationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Staff", "staff")
                        .WithMany("comments")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("registrationRequest");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("griffined_api.Models.CourseMember", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithMany("courseMembers")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudySubject", "studySubject")
                        .WithMany("courseMembers")
                        .HasForeignKey("studySubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("studySubject");
                });

            modelBuilder.Entity("griffined_api.Models.Level", b =>
                {
                    b.HasOne("griffined_api.Models.Course", "course")
                        .WithMany("levels")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("griffined_api.Models.NewCourseRequest", b =>
                {
                    b.HasOne("griffined_api.Models.Course", "course")
                        .WithMany("newCourseRequests")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Level", "level")
                        .WithMany("newCourseRequests")
                        .HasForeignKey("levelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithMany("newCourseRequests")
                        .HasForeignKey("registrationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("level");

                    b.Navigation("registrationRequest");
                });

            modelBuilder.Entity("griffined_api.Models.NewCourseSubjectRequest", b =>
                {
                    b.HasOne("griffined_api.Models.NewCourseRequest", "newCourseRequest")
                        .WithMany("newCourseSubjectRequests")
                        .HasForeignKey("newCourseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Subject", "subject")
                        .WithMany("newCourseSubjectRequests")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("newCourseRequest");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("griffined_api.Models.Parent", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithOne("parent")
                        .HasForeignKey("griffined_api.Models.Parent", "studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("griffined_api.Models.Payment", b =>
                {
                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithMany("payment")
                        .HasForeignKey("registrationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("registrationRequest");
                });

            modelBuilder.Entity("griffined_api.Models.PreferredDay", b =>
                {
                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("preferredDays")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("studyCourse");
                });

            modelBuilder.Entity("griffined_api.Models.PreferredDayRequest", b =>
                {
                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithMany("preferredDayRequests")
                        .HasForeignKey("registrationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("registrationRequest");
                });

            modelBuilder.Entity("griffined_api.Models.RegistrationRequestMember", b =>
                {
                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithMany("registrationRequestMembers")
                        .HasForeignKey("registrationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithMany("registrationRequestMembers")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("registrationRequest");

                    b.Navigation("student");
                });

            modelBuilder.Entity("griffined_api.Models.Schedule", b =>
                {
                    b.HasOne("griffined_api.Models.Appointment", "appointment")
                        .WithMany("schedules")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("appointment");
                });

            modelBuilder.Entity("griffined_api.Models.StaffNotification", b =>
                {
                    b.HasOne("griffined_api.Models.Staff", "staff")
                        .WithMany("staffNotifications")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("staffNotifications")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("staff");

                    b.Navigation("studyCourse");
                });

            modelBuilder.Entity("griffined_api.Models.StudentAddingRequest", b =>
                {
                    b.HasOne("griffined_api.Models.RegistrationRequest", "registrationRequest")
                        .WithOne("studentAddingRequest")
                        .HasForeignKey("griffined_api.Models.StudentAddingRequest", "registrationRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("studentAddingRequests")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("registrationRequest");

                    b.Navigation("studyCourse");
                });

            modelBuilder.Entity("griffined_api.Models.StudentAdditionalFile", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithMany("additionalFiles")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("griffined_api.Models.StudentAttendance", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithOne("attendance")
                        .HasForeignKey("griffined_api.Models.StudentAttendance", "studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyClass", "studyClass")
                        .WithMany("attendances")
                        .HasForeignKey("studyClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("studyClass");
                });

            modelBuilder.Entity("griffined_api.Models.StudentNotification", b =>
                {
                    b.HasOne("griffined_api.Models.Student", "student")
                        .WithMany("studentNotifications")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("studentNotifications")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("studyCourse");
                });

            modelBuilder.Entity("griffined_api.Models.StudentReport", b =>
                {
                    b.HasOne("griffined_api.Models.CourseMember", "courseMember")
                        .WithMany("studentReports")
                        .HasForeignKey("courseMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("studentReports")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courseMember");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.StudyClass", b =>
                {
                    b.HasOne("griffined_api.Models.Schedule", "schedule")
                        .WithOne("studyClass")
                        .HasForeignKey("griffined_api.Models.StudyClass", "scheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudySubject", "studySubject")
                        .WithMany("studyClasses")
                        .HasForeignKey("studySubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("studyClasses")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("schedule");

                    b.Navigation("studySubject");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.StudyCourse", b =>
                {
                    b.HasOne("griffined_api.Models.Course", "course")
                        .WithMany("studyCourses")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("griffined_api.Models.StudyCourseHistory", b =>
                {
                    b.HasOne("griffined_api.Models.Staff", "byStaff")
                        .WithMany("studyCourseHistories")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("studyCourseHistories")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("byStaff");

                    b.Navigation("studyCourse");
                });

            modelBuilder.Entity("griffined_api.Models.StudySubject", b =>
                {
                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("studySubjects")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Subject", "subject")
                        .WithMany("studySubjects")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("studyCourse");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("griffined_api.Models.Subject", b =>
                {
                    b.HasOne("griffined_api.Models.Course", "course")
                        .WithMany("subjects")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("griffined_api.Models.TeacherNotification", b =>
                {
                    b.HasOne("griffined_api.Models.Appointment", "appointment")
                        .WithMany("teacherNotifications")
                        .HasForeignKey("appointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.StudyCourse", "studyCourse")
                        .WithMany("teacherNotifications")
                        .HasForeignKey("studyCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("teacherNotifications")
                        .HasForeignKey("teacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("appointment");

                    b.Navigation("studyCourse");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.WorkTime", b =>
                {
                    b.HasOne("griffined_api.Models.Teacher", "teacher")
                        .WithMany("workTimes")
                        .HasForeignKey("teacherId");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("griffined_api.Models.Appointment", b =>
                {
                    b.Navigation("appointmentMembers");

                    b.Navigation("schedules");

                    b.Navigation("teacherNotifications");
                });

            modelBuilder.Entity("griffined_api.Models.Course", b =>
                {
                    b.Navigation("levels");

                    b.Navigation("newCourseRequests");

                    b.Navigation("studyCourses");

                    b.Navigation("subjects");
                });

            modelBuilder.Entity("griffined_api.Models.CourseMember", b =>
                {
                    b.Navigation("studentReports");
                });

            modelBuilder.Entity("griffined_api.Models.Level", b =>
                {
                    b.Navigation("newCourseRequests");
                });

            modelBuilder.Entity("griffined_api.Models.NewCourseRequest", b =>
                {
                    b.Navigation("newCourseSubjectRequests");
                });

            modelBuilder.Entity("griffined_api.Models.RegistrationRequest", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("newCourseRequests");

                    b.Navigation("payment");

                    b.Navigation("preferredDayRequests");

                    b.Navigation("registrationRequestMembers");

                    b.Navigation("studentAddingRequest");
                });

            modelBuilder.Entity("griffined_api.Models.Schedule", b =>
                {
                    b.Navigation("studyClass")
                        .IsRequired();
                });

            modelBuilder.Entity("griffined_api.Models.Staff", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("staffNotifications");

                    b.Navigation("studyCourseHistories");
                });

            modelBuilder.Entity("griffined_api.Models.Student", b =>
                {
                    b.Navigation("additionalFiles");

                    b.Navigation("address");

                    b.Navigation("attendance");

                    b.Navigation("cancellationRequests");

                    b.Navigation("courseMembers");

                    b.Navigation("parent");

                    b.Navigation("registrationRequestMembers");

                    b.Navigation("studentNotifications");
                });

            modelBuilder.Entity("griffined_api.Models.StudyClass", b =>
                {
                    b.Navigation("attendances");

                    b.Navigation("cancellationRequests");
                });

            modelBuilder.Entity("griffined_api.Models.StudyCourse", b =>
                {
                    b.Navigation("cancellationRequests");

                    b.Navigation("preferredDays");

                    b.Navigation("staffNotifications");

                    b.Navigation("studentAddingRequests");

                    b.Navigation("studentNotifications");

                    b.Navigation("studyCourseHistories");

                    b.Navigation("studySubjects");

                    b.Navigation("teacherNotifications");
                });

            modelBuilder.Entity("griffined_api.Models.StudySubject", b =>
                {
                    b.Navigation("courseMembers");

                    b.Navigation("studyClasses");
                });

            modelBuilder.Entity("griffined_api.Models.Subject", b =>
                {
                    b.Navigation("newCourseSubjectRequests");

                    b.Navigation("studySubjects");
                });

            modelBuilder.Entity("griffined_api.Models.Teacher", b =>
                {
                    b.Navigation("appointmentMembers");

                    b.Navigation("cancellationRequests");

                    b.Navigation("studentReports");

                    b.Navigation("studyClasses");

                    b.Navigation("teacherNotifications");

                    b.Navigation("workTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
